// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooAPI.Datas;

#nullable disable

namespace ZooAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230921101533_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooCore.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Espece")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Description = "Elephant",
                            Espece = 3,
                            ImageURL = "/images/bacon.jpg",
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 2,
                            Age = 10,
                            Description = "Tigre Lardon",
                            Espece = 5,
                            ImageURL = "/images/bacon.jpg",
                            Name = "Lardon"
                        },
                        new
                        {
                            Id = 3,
                            Age = 15,
                            Description = "Dromadaire Jambon",
                            Espece = 4,
                            ImageURL = "/images/bacon.jpg",
                            Name = "Jambon"
                        },
                        new
                        {
                            Id = 4,
                            Age = 20,
                            Description = "Serpent Saucisson",
                            Espece = 6,
                            ImageURL = "/images/bacon.jpg",
                            Name = "Saucisson"
                        });
                });

            modelBuilder.Entity("ZooCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "2 rue tartempion 55555 Bidule",
                            Email = "root@pokecorp.com",
                            FirstName = "Root",
                            IsAdmin = true,
                            LastName = "ROOT",
                            PassWord = "UEFzczAwKytsYSBjbMOpIHN1cGVyIHNlY3LDqHRlIGRlIGxhIHBva2Vtb24gYXBp",
                            PhoneNumber = "01 01 01 01 01"
                        },
                        new
                        {
                            Id = 2,
                            Address = "10 rue tartempion 55555 Turlututu",
                            Email = "curentuser@pokecorp.com",
                            FirstName = "Current",
                            IsAdmin = false,
                            LastName = "User",
                            PassWord = "UEFzczAwKytsYSBjbMOpIHN1cGVyIHNlY3LDqHRlIGRlIGxhIHBva2Vtb24gYXBp",
                            PhoneNumber = "02 02 02 02 02"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
